project_id = "szmflagbbuxcuuxpvnkt"

[functions.ai-search]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-traffic-data]
verify_jwt = false

[functions.analyze-nearby-poi]
verify_jwt = false

[functions.get-tomtom-layers]
verify_jwt = false

[functions.analyze-inegi-data]
verify_jwt = false
